### ISSUE TITLE
Disable Menu bar during processing

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/DataspaceConnectorUI#102]
Hi,
I have noticed strange behavior when pressing on a menu item on the left during resource creation, for example.
Often the UI spins and sometimes the DSC spins as well.
I would suggest that you not only disable the main window, as is currently the case, but also prohibit clicking in the menu.

**Comment by BastianWel** [comment]
I could not reproduce the error, but perhaps the error was also related to the automatic invocation of the "Data Offering > IDS Resource" page after saving.
Since d4ca375 the navigation menu blocks until the resource was saved.
