### ISSUE TITLE
A connector registered at bootstrap cannot be de/registered with the UI

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#111]
1. Start a fresh connector that registers its resources during bootstrap.
2. After starting the connector go to the Broker view in the UI (it will be empty)
3. In the Broker view add the Broker where the resources have been registered already.
4. Click the register button
This will fail since the broker has registered itself during bootstrap. The register button will never become available.

I think there are also other scenarios where a connector is registered but the button has the wrong state.

**Comment by BastianWel** [comment]
Is there an error message in the DSC log?
Does it work with DSC Swagger?

**Comment by sebplorenz** [comment]
Hi @BastianWel ,
the thing is that in step 4 the button is in the wrong state.
Expected behavior: The button text is "unregister" if the connector is already registered.

**Comment by BastianWel** [comment]
The status of the button is determined by the "status" attribute of the broker object in the API call "GET /api/brokers".
Could you check if the DSC is returning the correct registration status?

**Comment by tmberthold** [comment]
Will be fixed in Dataspace Connector.

**Comment by tmberthold** [comment]
Fixed on Dataspace Connector main.
