### ISSUE TITLE
No payment modalities listed

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#114]
Tested with DSC 6.2 and UI 8.5.1
When creating a new resource or editing an existing resource no payment modalities are listed:

![grafik](https://user-images.githubusercontent.com/4161673/135999901-eae02bd2-1463-49bf-b58b-4f4c1b77e3e2.png)

**Comment by BastianWel** [comment]
You need to update to DSC 6.3.0

**Comment by sebplorenz** [comment]
Yes, I just tested and it works with 6.3.0
