### ISSUE TITLE
Cannot un-publish a resource

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#119]
When creating or editing an offered resource I am not able to finish the wizard without selecting a Broker to publish the resource to. 

![grafik](https://user-images.githubusercontent.com/4161673/140704658-367e2d26-a4bc-44ee-acca-3fbec7509da3.png)

Expected: The NEXT button should be available even if no Broker has been selected. Because it is common use-case to not publish a resource in the first place or to unpublish it after it has been published.

**Comment by BastianWel** [comment]
You are on the catalog page. 
Each resource must be assigned to a catalog in the UI.
