### ISSUE TITLE
Create broker failed message when creating an App Store entry (v8.8.0)

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#124]
![grafik](https://user-images.githubusercontent.com/4161673/151517061-f37998a0-8136-4c2b-931e-5b16cb89b472.png)

**Comment by BastianWel** [comment]
Error message was corrected in b196902.
Error does not occur with DSC 6.5.3.
If DSC 7.0.0 was used, then please test again with 6.5.3.
