### ISSUE TITLE
Agreements do not open up (v. 8.0.0)

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#125]
Clicking on an agreement loads endless:

![grafik](https://user-images.githubusercontent.com/4161673/151526002-ebe78715-c29f-46b8-844b-b4a187261a82.png)

**Comment by BastianWel** [comment]
I cannot reproduce the error. 
Can you send the log outputs from UI (browser console) and DSC?

**Comment by BastianWel** [comment]
I suspect that DSC 7.0.0 was also used here, which is not compatible with UI 8.8.0.
If the error also occurs with DSC 6.5.3, please reopen the issue.
