### ISSUE TITLE
Wrong settings in UI v. 8.0.0

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#126]
When I check the Settings page of my DSC 7.0.0 it shows old values. The connector version, inbound and outbound model versions are not up-to-date.
![grafik](https://user-images.githubusercontent.com/4161673/151529461-50cdd6e4-83a9-4bf3-83c9-3fe82798298f.png)

**Comment by BastianWel** [comment]
UI 8.0.0 is not compatible with DSC 7.0.0.
Please use DSC 6.5.3
