### ISSUE TITLE
Get payment methods failed. v 8.0.0

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#127]
With a fresh DSC 7.0.0 setup when opening Offered Resources, error messages for payment, security profiles, payment methosds appears.
![grafik](https://user-images.githubusercontent.com/4161673/151545998-7446e708-6c21-45a6-875e-346eb0974904.png)

**Comment by BastianWel** [comment]
This is because the UI 8.8.0 is incompatible with the DSC 7.0.0 API. DSC 6.5.3 must be used.
A UI (9.0.0) compatible to DSC 7.0.0 is coming soon.
