### ISSUE TITLE
Get backend connections failed UI 9.0.0 with DSC 7.0.3

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#134]
No messages in the connector logs. Only this in the frontend.

![grafik](https://user-images.githubusercontent.com/4161673/157389484-d4ac8cae-4aa3-4fbe-a2b5-4d641ca9a4d1.png)

**Comment by BastianWel** [comment]
Has been fixed in 7fe7255.
Will be available with next release.
