### ISSUE TITLE
DSC admin password can be seen in the DSC UI

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#135]
The DSC UI backend returns username and password in the response to the DSC UI frontend in case of an error.
Eg. if you enter a wrong provider URL when requesting a resource list:

![grafik](https://user-images.githubusercontent.com/4161673/157395347-476587e8-db21-45c9-ac3a-54582b6d217e.png)

**Comment by BastianWel** [comment]
Fixed in 48f6017.
Will be available with next release.
