### ISSUE TITLE
Dont register Broker automatically when new Broker added to GUI

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/DataspaceConnectorUI#20]
Currently, the connector is automatically registered at a new Broker, if a new Broker is added in the GUI.

Problem: GUI calls API to register at Broker directly after adding.

![image](https://user-images.githubusercontent.com/75306992/111774519-da6a8380-88af-11eb-864c-394398199cdf.png)

**Comment by BastianWel** [comment]
I remember that the requirement was to register directly with the newly created broker. Why should the registration be removed?
