### ISSUE TITLE
Can't connect the DataspaceConnectorUI to a DataspaceConnector

### ISSUE THREAD

**Issue by ValentinaIvanova** [International-Data-Spaces-Association/DataspaceConnectorUI#283]
Hello!

I have successfully deployed the IDS testbed and run the tests described here https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/PreparingPreconfiguredSetup.md#guide-for-preparing-and-validating-the-preconfigured-setup
I would like to use the DataspaceConnectorUI to provide interface for one of the connectors in the testbed. I built and run the DataspaceConnectorUI with docker and changed host, port and authentication values in the docker-compose in order to correspond to those used by one of the connectors in the testbed. 

I can successfully reach the DataspaceConnectorUI user interface. However, the connector I specified is not present/shown anywhere in the UI. In the DataspaceConnectorUI container logs I can see multiple unsuccessful requests to the different connector's endpoints where the error messages look similarly to this one.
Error on GET /api/catalogs AxiosError: connect ECONNREFUSED 127.0.0.1:8888
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {

Additionally, I get similar error messages if I try to add the connector or a broker through the UI. 

Looking forward to your advice how to resolve this error.

Thank you in advance!
Valentina

**Comment by SebastianOpriel** [comment]
I think you may have issues with the correct port. I do not see any port 8888 exposed at https://github.com/International-Data-Spaces-Association/IDS-testbed/blob/master/docker-compose.yml

**Comment by ValentinaIvanova** [comment]
Hi Sebastian,

I have exposed 8888 as I have other apps using 8080.

Thanks,
Valentina

**Comment by SebastianOpriel** [comment]
Maybe those deploy examples help you to find the issue and get it up an running: https://github.com/Mobility-Data-Space/Deployment-Examples
As side note: sovity offers DSCs and UIs as a fully configured and ready to use SaaS solution.

**Comment by ValentinaIvanova** [comment]
Thank! It was a port config, at the end.
