### ISSUE TITLE
Show warning before deleting a backend connection / resource

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/DataspaceConnectorUI#32]
In the GUI, created backend connection can be easily deleted, regardless of whether they are used in routes or not.

The same applies to resources that are considered endpoints of routes.

If backend-connections and/or resources that are used in routes are deleted, the routes will be broken and can only throw errors in the backend/connector.

A broken route with missing backend-connection and resource, which were deleted after creating the route, can look like this:

![image](https://user-images.githubusercontent.com/75306992/112985534-97869680-9160-11eb-8e7e-d87fa67049b2.png)

**Comment by BastianWel** [comment]
Maybe displaying a warning is not enough. We would have to discuss whether the associated routes and corresponding resources should also be deleted in order to avoid incomplete data.

**Comment by BastianWel** [comment]
Associated routes of the backend connection are now deleted and a warning is displayed in the dialog (876a85a)
