### ISSUE TITLE
Check connection to Configmanager & Connector on startup

### ISSUE THREAD

**Issue by BastianWel** [International-Data-Spaces-Association/DataspaceConnectorUI#36]
When loading the main Page, check the connection to CM/Connector.
Maybe a new CM API to return connector connection status. Call with timeout:
Timeout = No connection to CM
Response "false" = No connection to Connector

**Comment by tmberthold** [comment]
Waiting for:
https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/90

**Comment by tmberthold** [comment]
New CM-API (currently dev-Branch):
https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager/issues/90

```
@GetMapping(value = "/connector/status", produces = "application/ld+json")
@Operation(summary = "Get the accessibility-status of the Public Connector Endpoint (Connector Self-description)")
@ApiResponses({
       @ApiResponse(responseCode = "200", description = "Public connector endpoint reachable."),
       @ApiResponse(responseCode = "503", description = "Public connector endpoint not reachable.")})
ResponseEntity<String> getConnectorStatus();
```
