### ISSUE TITLE
Run application in docker as non-root user

### ISSUE THREAD

**Issue by DominikPinsel** [International-Data-Spaces-Association/DataspaceConnectorUI#39]
For security reasons it's always a good idea to run the application inside docker as non-root user.

Its possible to do this in docker by
- creating a user & group
- creating a new directory
- giving group access to the directory and make it executable
- using the newly created user to run the application

Something like this:
```
RUN addgroup --gid 6555 ids-nonroot
RUN adduser --gid 6555 --uid 6555 ids-nonroot
RUN mkdir /usr/src/app
RUN chgrp -R ids-nonroot /usr/src/app
RUN chmod -R 770 /usr/src/app

USER ids-nonroot

WORKDIR /usr/src/app

.. copy & run app ..
```

<sub> Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by BastianWel** [comment]
Fixed in b3188f8
