### ISSUE TITLE
Provide overall docker-compose example

### ISSUE THREAD

**Issue by mikhail-gordienko** [International-Data-Spaces-Association/DataspaceConnectorUI#48]
Hello!

Would be nice to have a docker-compose.yml with all components gathered together:

- connector
- configmanager
- configmanager-ui

and with all environment variables configured properly.

**Comment by tmberthold** [comment]
Available since yesterday:
https://github.com/International-Data-Spaces-Association/IDS-Deployment-Examples/tree/main/dataspace-connector/full

**Comment by mikhail-gordienko** [comment]
Great! Thank you!
