### ISSUE TITLE
Enable data consumption

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/DataspaceConnectorUI#66]
Enable data consumption by following [these steps](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/Consumer) via UI:

- [ ] [Request a Connector’s Self-description ](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/Consumer#step-1-request-a-connectors-self-description) - User insert the recipient ID
- [ ] User select element (so UI get the element ID)
- [ ] [Request Metadata](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/Consumer#step-2-request-metadata) - Show user the Metadata
- [ ] [Negotiate a Contract Agreement ](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/Consumer#step-3-negotiate-a-contract-agreement) - [display contract: Rule and license] User accept or deny the Contract.
- [ ] Display the user the path to get the consumed data: [Access Data](https://international-data-spaces-association.github.io/DataspaceConnector/CommunicationGuide/Consumer#step-4-access-the-data) (e.g. https://localhost:8080/api/artifacts/{id}/data with inserted ID)

**Comment by BastianWel** [comment]
Available since version 8.3.0
