### ISSUE TITLE
Query Broker to get recipient ID for data consumption

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/DataspaceConnectorUI#68]
Beside the manual input of an recipient ID during data consumption see #66 , there should be a possibility to search for data in the metadata broker.
For example like that:
- Manual recipient ID input field
- Search field to browse a selected Broker
- List of Broker results (User can select a resource like in the manual version, directly bring the user to a selected recipient ID and resource)

**Comment by HeinrichPet** [comment]
Use broker full text search: /api/ids/search

**Comment by BastianWel** [comment]
The current API responses of the broker search do not allow access to the data from the DSC, therefore implementations in the broker are necessary before the broker full text search can be implemented in the UI.

**Comment by BastianWel** [comment]
Implemented in 79dbaac
