### ISSUE TITLE
Add contract classes "Restrict to specific Security Level"

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/DataspaceConnectorUI#69]
Add Policy to the UI for "restrict to specific Security Levels".
User can select idsc:TRUST_SECURITY_PROFILE or idsc:BASE_SECURITY_PROFILE or idsc:TRUST_PLUS_SECURITY_PROFILE

**Comment by BastianWel** [comment]
Added in 5b9c0d3
