### ISSUE TITLE
Allow pricing modalities

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/DataspaceConnectorUI#71]
Various pricing modalities such as "free", "fixed price", "negotiation basis" can be used as a pre-selection to annotate the terms of the contract. Depending on the requirements, additional free text information can be attached.

See: https://github.com/International-Data-Spaces-Association/DataspaceConnector/issues/439

**Comment by BastianWel** [comment]
Implemented in 1de7469
