### ISSUE TITLE
Renaming ConnectorEndpoint -> DefaultEndpoint

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/DataspaceConnectorUI#81]
On the DSC main, in the configuration (Settings page of the UI), the ConnectorEndpoint has been renamed to DefaultEndpoint, would need to be changed along in the UI. Currently nothing is displayed at the endpoint info on the settings page due to this.

SettingsPage.html changes:
![image](https://user-images.githubusercontent.com/75306992/126864143-8c67aa2e-745a-4514-8554-c646ade362be.png)

SettingsPage.js changes:
![image](https://user-images.githubusercontent.com/75306992/126864148-860cfe51-9670-4118-b640-8ecd4a9a239c.png)

clientDataModel.js changes:
![image](https://user-images.githubusercontent.com/75306992/126864165-7c1dafc2-141a-413a-9125-174c1e2816ed.png)

After the above adjustments, it works locally for me again.

I think next time I'll open a PullRequest directly 😄

**Comment by BastianWel** [comment]
Thank you, I changed it in a08c9cd
