### ISSUE TITLE
Creating Camel routes when saving a Resource with external Backend-Connection

### ISSUE THREAD

**Issue by tmberthold** [International-Data-Spaces-Association/DataspaceConnectorUI#85]
If an external URL is specified in the backend connection regardless of the choice Database/Rest, when sending the backend-connection-accessUrl in the new artifact as a consequence when saving a resource via the UI, the DSC understands this new artifact as RemoteData instead of LocalData, whereby the Camel route is no longer functional and encounters a NotImplemented in the DSC and accordingly terminates with an Internal Error 500.
https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/cc2d8fd87a835d848b078d8bfa998a49d97eb610/src/main/java/io/dataspaceconnector/service/resource/type/ArtifactService.java#L395

Would have to be adapted either on the side of the UI or in the DSC.

_The fact that this is written in the UI does not necessarily mean that it must be adjusted there, depends on the solution we find._

**Comment by BastianWel** [comment]
Should be fixed with 82dc712
