### ISSUE TITLE
Recipient URL for data consumption

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#88]
I assume the 'Provider Connector URL' is meant here:

![recipient_url](https://user-images.githubusercontent.com/4161673/129156687-e68aafc3-bfb1-4183-b432-a387b39010a7.png)

In addition, it would be helpful if an example would be given that highlights if the path '/api/ids/data' should be added or not.

**Comment by BastianWel** [comment]
Changed in #b0117c5
