### ISSUE TITLE
Informative error messages, please

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#89]
When selecting 'Receive Resources' in the 'Add Resource' view I'm getting the error message:
```
Receive resources failed. (See logs for details) 
```
This is not very informative. In addition, a normal UI user might not have access to the infrastructure to check the logs.
Looking into the looks reveals the following information:
```
Message handling or processing failed.
```
Well, sure. I already know.

As a user I would expect error messages that help me to find the reason of the error to be able to fix it (e.g. if there is no provider service available at the given URL). Or that help the administrator to narrow down the possible reasons for the error.

**Comment by BastianWel** [comment]
"Message handling or processing failed." is the error message the UI gets from DSC.
I do not have more information in the UI.
