### ISSUE TITLE
Wrong Download Link

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#94]
In the "Receive Recources" view, when creating a new resource consumption, the download link that is shown at the end is wrong.
The link points to the API of the provider connector.
Expected: The link should point to the API of the consumer connector. (To the API of the connector that the UI is connected to.)

In the following picture, the download link at the bottom of the page points to the API of the remote (provider) connector. But it should point to the API of this connector (which is not the DWD connector):
![connector_ui_dowload_link](https://user-images.githubusercontent.com/4161673/129716729-1fdf99cb-579c-4f22-baa5-98fb2ee8605c.jpg)

**Comment by BastianWel** [comment]
Fixed in 0eab4d3.
Will be available with next release.
