### ISSUE TITLE
Consumed resources created using the UI are not visible in the UI

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#95]
I created a resource using the "Create Resources" button in the "Data Consumption" > "IDS Resources" view.
The creation of the resource was successful and it is consumed by backend applications of the consumer connector. But the resource is not shown in the "Data Consumption" > "IDS Resources" view.

**Comment by BastianWel** [comment]
Implemented in a024480.
Will be available with next release.
