### ISSUE TITLE
Show Catalog title if available

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/DataspaceConnectorUI#96]
In Data consumption:
Catalog titles are not mandatory.
However it will help the user if there is a title to show it instead of the catalog ID.

**Comment by BastianWel** [comment]
Because catalog titles are missing in the info model, the UI could only display catalog IDs.
Therefore, all resources are now directly displayed.
The catalog selection could be added again as soon as catalog titles are available in the info model.
