### ISSUE TITLE
Broker cannot be added if used in bootstrap sequence

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#97]
If DSC bootstrapping is used and resources are added to a broker during bootstrap, then the broker used in the bootstrap sequence can neither be seen in the Broker view of the UI nor can it be added using the "Add Broker" button. After entering the Broker URL in the "Add Broker" dialog and clicking "Save" the dialog disappears and the Broker does not appear in the list of brokers.
As said before, this only happens if resources are added to the Broker during the bootstrap sequence. If resources are not added to a broker during the bootstrap sequence then the broker URL can be added using the UI without problems.

**Comment by BastianWel** [comment]
Tested bootstrapping with example files ("src/test/resources/bootstrap") which include registering resources at https://broker.ids.isst.fraunhofer.de/infrastructure.
After the startup with bootstrap adding "https://broker.ids.isst.fraunhofer.de/infrastructure" as broker via UI worked for me.

That brokers from bootstrap are not automatically added to the DSC brokers is an DSC feature (not UI) that needs to be implemented if needed.
